baseURL = 'https://konkasidiaris.com/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = "Kon's Internet Corner"
enableRobotsTXT = true
buildFuture = true
hrefTargetBlank = true
disableHugoGeneratorInject = true

[frontmatter]
  date = ['publishDate']

[taxonomies]
  tag = "tags"

[params]
  logo = "/images/logo.jpg"
  description = 'Building scalable infrastructure, automating everything, and sharing platform engineering insights'

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
    [menu.main.params]
      svg = 'svg/identification.html'
  [[menu.main]]
    name = 'Blog'
    pageRef = '/posts/'
    weight = 2
    [menu.main.params]
      svg = 'svg/newspaper.html'
  [[menu.main]]
    name = 'Projects'
    pageRef = '/projects/'
    weight = 3
    [menu.main.params]
      svg = 'svg/cpu-chip.html'
  [[menu.main]]
    name = 'Résumé'
    pageRef = '/resume/'
    weight = 4
    [menu.main.params]
      svg = 'svg/queue-list.html'
  [[menu.contact]]
    name = 'Github'
    url = 'https://github.com/konkasidiaris'
    weight = 1
    [menu.contact.params]
      svg = 'svg/github.html'
  [[menu.contact]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/konstantinos-kasidiaris/'
    weight = 1
    [menu.contact.params]
      svg = 'svg/linkedin.html'
  [[menu.contact]]
    name = 'X'
    url = 'https://x.com/konkasidiaris'
    weight = 1
    [menu.contact.params]
      svg = 'svg/x.html'
  [[menu.contact]]
    name = 'email'
    url = 'mailto:kkasidiaris@gmail.com'
    weight = 1
    [menu.contact.params]
      svg = 'svg/envelope.html'
  
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = false
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = false
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
      version = 2022
    [minify.tdewolff.json]
      keepNumbers = false
      precision = 0
    [minify.tdewolff.svg]
      keepComments = false
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']
